### ISSUE TITLE
how to save well-trained model?

### ISSUE THREAD

**Issue by chenwgen** [williamleif/GraphSAGE#1]
Hi,I use the save method of the model to keep well-trained models,but there were the following mistakes：
>  raise ValueError("No variables to save")
> ValueError: No variables to save

So how do I keep well-trained models ,thanks!

**Comment by williamleif** [comment]
Hmm, this seems like it could be an issue with how you are setting up the graph. In particular, it might be that your Saver object is not properly associated with the TensorFlow graph that contains all the variables. Or a least, this StackOverflow post seems to suggest that this is the case: 

https://stackoverflow.com/questions/38626435/tensorflow-valueerror-no-variables-to-save-from   

Could you post some more context for your code?

**Comment by Phil-U-U** [comment]
Hi Will/Rex, 

I have exactly the same error as above. It came from saver = tf.train.Saver(self.vars) in the following method of class Model in models.py. And it was because I added this line of code after all the epochs were successfully run i.e. for epoch in range(FLAGS.epochs) in the unsupervised_train.py : model.save(sess, log_dir())

    def save(self, sess=None, save_path=None):
        if not sess:
            raise AttributeError("TensorFlow session not provided.")
        saver = tf.train.Saver(self.vars)
        if save_path:
            file_path = saver.save(sess, save_path + "%s.ckpt" % self.name )
        else:
            file_path = saver.save(sess, "./%s.ckpt" % self.name)
        print("Model saved in file: %s" % file_path)

**Comment by shivam1702** [comment]
Hi @chenwgen how did you manage to resolve the issue? 
I am struggling to save the model. 
Using `tf.saved_model.save(model, model_dir)`
if gives me `    	ValueError: Expected a Trackable object for export, got <graphsage.models.SampleAndAggregate object at 0x7fd1072e8a90>.`
