### ISSUE TITLE
The train data and valid data have no intersection. Then how does the valid data get the embedding for downstream model?

### ISSUE THREAD

**Issue by guotong1988** [williamleif/GraphSAGE#111]
Based on my understanding, it seems that train nodes are [1,2,3,4,5] and valid nodes are [6,7]. We are training on [1,2,3,4,5], then how does [6,7] get the embedding for downstream model?

Thank you very much!

**Comment by RexYing** [comment]
Hi, the embeddings for [6,7] are computed as a function of the input feature of [6, 7]. The learned function is parameterized by the GraphSAGE neural network that was learned from [1, 2, 3, 4, 5] and their connectivity. 

If there is no node features, constant/degree features can be used for all nodes [1 .. 7]

**Comment by guotong1988** [comment]
Thank you very much.
Could you please point out the code lines corresponding to your answer.
Thank you again!

**Comment by guotong1988** [comment]
From the code https://github.com/williamleif/GraphSAGE/blob/master/graphsage/models.py

![image](https://user-images.githubusercontent.com/4702353/69222676-ec9dba00-0bb4-11ea-979c-f462f6a88d20.png)

It seems that no info is shared between training and predicting.

**Comment by kameshso01** [comment]
Hey could you tell me how can I get the embeddings in supervised mode, SAVED!

**Comment by guotong1988** [comment]
I understand now. 
The graph connections/topology info is somehow re-used for predict unseen nodes' final embedding.
The init embedding is from Glove wordvec or something.
