### ISSUE TITLE
Create data fits with utils.py

### ISSUE THREAD

**Issue by DLH06** [williamleif/GraphSAGE#122]
Hi. I have some own documents that I really wanna use them as my dataset. How can I convert them into type that it will fit with utils.py. I try to see what's inside your example_data folder. However, there are some many complicated things I can't understand :((

**Comment by silent-code** [comment]
Check out [StellarGraph ](https://stellargraph.readthedocs.io/en/stable/README.html#algorithms) which implements the GraphSAGE algorithm and is user friendly and well-documented. [Here ](https://orbifold.net/default/using-graphsage-for-node-predictions/)is a StellarGraph GraphSAGE examples on how to load in data and do node inference.
