### ISSUE TITLE
 No such file or directory: './example_data/ppi-G.json' 

### ISSUE THREAD

**Issue by universewill** [williamleif/GraphSAGE#131]
when i run example_unsupervised.sh , i got and error:
 No such file or directory: './example_data/ppi-G.json' 

Where to get the data file?

**Comment by chestnzu1** [comment]
Hello:
       I have met the same problem. Can you tell me how you solved it? Thank you.

**Comment by zeou1** [comment]
> Hello:
> I have met the same problem. Can you tell me how you solved it? Thank you.

I think you need to get the datafile from the [GraphSAGE website](http://snap.stanford.edu/graphsage/)

**Comment by chestnzu1** [comment]
> > Hello:
> > I have met the same problem. Can you tell me how you solved it? Thank you.
> 
> I think you need to get the datafile from the [GraphSAGE website](http://snap.stanford.edu/graphsage/)

Hello Zou1:
             Thank you for your answer. I have solved the problem by changing the directory from './example_data/ppi-G.json' to './example_data/toy-ppi-G.json'. The creator have modified the name of the file in the example data.

**Comment by zeou1** [comment]
> > > Hello:
> > > I have met the same problem. Can you tell me how you solved it? Thank you.
> > 
> > 
> > I think you need to get the datafile from the [GraphSAGE website](http://snap.stanford.edu/graphsage/)
> 
> Hello Zou1:
> Thank you for your answer. I have solved the problem by changing the directory from './example_data/ppi-G.json' to './example_data/toy-ppi-G.json'. The creator have modified the name of the file in the example data.

Yes, but the toy dataset is a smaller version of the ppi-G dataset
