### ISSUE TITLE
How to train on bipartite graph?

### ISSUE THREAD

**Issue by universewill** [williamleif/GraphSAGE#138]
Can this graphsage model support bipartite graph training? Like user-item graph?

**Comment by sam-lev** [comment]
Training on a bipartite shouldn't pose different problems. Alternatively one could follow pinsage which is bipartite: [pinsage](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjC-aj27-jpAhUzj3IEHQOVBMQQFjAAegQIARAB&url=https%3A%2F%2Farxiv.org%2Fpdf%2F1806.01973&usg=AOvVaw0OaRReMuqXgGEN_6Z9ZmlC)

**Comment by universewill** [comment]
> Training on a bipartite shouldn't pose different problems. Alternatively one could follow pinsage which is bipartite: [pinsage](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjC-aj27-jpAhUzj3IEHQOVBMQQFjAAegQIARAB&url=https%3A%2F%2Farxiv.org%2Fpdf%2F1806.01973&usg=AOvVaw0OaRReMuqXgGEN_6Z9ZmlC)

Do you mean that the graph conv encoder would handle the difference between user and item node by itself? Yeah, i think maybe it's right.

 It seems that there is no source code for pinsage model.

**Comment by sam-lev** [comment]
Graphsage should implicitly handle the graph being bipartite but if you wanted to incorporate more importance on the node roles you could add feature definitions / labels (for supervised training) to the nodes based on whether or not they are a user or item nodes but the 'user-item' relation between nodes should be captured by the aggregators during training. @universewill
