### ISSUE TITLE
Across graphs learning example

### ISSUE THREAD

**Issue by kwonoh** [williamleif/GraphSAGE#17]
Hi William,

Are there example code and data for the across learning example described in section 4.2 in your paper?
Currently, the PPI data and evaluation code seem like a single graph example.
Thank you very much for sharing the resources!

Cheers,
Oh-Hyun

**Comment by williamleif** [comment]
Hi Oh-Hyun,

Thanks for the question! The PPI data is actually "across graph". For simplicity, we just represent the set of different networks as one big network that has different independent components. This is really just for ease-of-coding and storing the data, but it is still in fact "across graph."

Best,
Will

**Comment by kwonoh** [comment]
Hi Will,

Thank you very much for the information! 

Best,
Oh-Hyun
