### ISSUE TITLE
End of mini batch iteration 

### ISSUE THREAD

**Issue by Songweiping** [williamleif/GraphSAGE#18]
Hi,
I am a little confused by this line.
https://github.com/williamleif/GraphSAGE/blob/811b50945e8768a6c2255171e40549d43eb8b66d/graphsage/minibatch.py#L111
what does `+ 1` mean? Is this intentional for any boundary conditions?

Thanks.

**Comment by RexYing** [comment]
Yes this is to avoid index out of bound. 
I have modified the code just now to allow the size of the last batch to be any positive integer less than self.batch_size, so that all examples are seen at every epoch

**Comment by Songweiping** [comment]
Your modifications are cool and the size of last batch can be any positive integer now. Thanks for the efforts!

However, I still can not figure out why `+ 1` in original code. Suppose there are 100 training edges, with batch_size set to 1. Your original code would produce 101 batches, where the last batch is empty. Would you please give an instance when  `+ 1` helps?

**Comment by RexYing** [comment]
I see. Yes the +1 in the code before didn't seem necessary. Thanks for pointing it out!
