### ISSUE TITLE
Saving GraphSAGE model -- ValueError: GraphDef cannot be larger than 2GB

### ISSUE THREAD

**Issue by laurimi** [williamleif/GraphSAGE#19]
I am trying to save the model obtained by running GraphSAGE on a graph with a large number of nodes (in the order of few million nodes). I would like to use the model later on data not in the original training, validation or test sets. I tried using a [`tf.Saver`](https://www.tensorflow.org/api_docs/python/tf/train/Saver) object as follows, in `supervised_train.py`:
```
saver = tf.train.Saver()
for epoch in range(FLAGS.epochs):
    // training loop body goes here
    saver.save(sess, os.path.join(log_dir(), "model.ckpt"), global_step=total_steps)
```
This worked nicely for some of the small examples I tried, but now I am facing an error message saying the GraphDef to be written is too large:
```
<cut off a bunch of lines of traceback>

  File "/work/GraphSAGE/graphsage/supervised_train.py", line 272, in train
    saver.save(sess, os.path.join(log_dir(), "model.ckpt"), global_step=total_steps)
  File "tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1494, in save
    self.export_meta_graph(meta_graph_filename)
  File "tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1522, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2361, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2324, in _as_graph_def
    raise ValueError("GraphDef cannot be larger than 2GB.")
ValueError: GraphDef cannot be larger than 2GB.
```

I tried to cut down on the amount of data to save by specifying `tf.Saver` to only write the trainable parameters:
```
saver = tf.train.Saver(var_list=tf.trainable_variables())
```
However, the error persists.

Any ideas how I could save the necessary parts of the computational graph to be able to later load it from disk and apply it to new data?

**Comment by laurimi** [comment]
I was able to save the models to disk once I realized the graph adjacency and the features were also being written, as they are defined via `tf.Constant`. This was pushing the size of the graph over the limit. To avoid saving these constants, I used `tf.placeholder` in their place instead.

The change for supervised models can be seen in [this commit in my fork](https://github.com/laurimi/GraphSAGE/commit/ff678a70f685e8ac2471e979acc3b3605efad99f). Happy to put in a pull request if you think there are no obvious downsides.

**Comment by RexYing** [comment]
Hi, sorry for the late reply since we are at conference.

What you said is indeed the case. Using placeholder for adj will solve the problem. However, we were concerned that there would be significant overhead when feeding in the same np array at each iteration.
In fact when I was using GraphSAGE for extremely large datasets (10^9 scale), I set the adj as a variable, and feed it in only at the start of training/validation/test.

But of course ideally we would want tensorflow to avoid the overhead when feeding the same array without modifications, so that placeholder would be the most elegant solution.

Rex

**Comment by williamleif** [comment]
@RexYing what is the final word on this? I suppose our current implementation in master branch is the simplest, but has the issue that the adjacency matrix is treated as part of the graph. I don't think having the adjacency as a placeholder is best because of the data I/O overhead, but maybe we should have a helper function or something that makes it easier to save the model?

**Comment by laurimi** [comment]
Shouldn't it be enough to assign the adjacency matrix placeholder once, before starting the training loop? Further I/O could be avoided also for validation/test sets if another instance of the learned model is created, and only the learned weights are copied to this instance when validation/testing is to be performed. Copying the weights should be orders of magnitude cheaper than swapping the adjacency matrix.

**Comment by williamleif** [comment]
@RexYing do you have thoughts on @laurimi's solution above? You have more experience dealing with this I/O overhead issue, but her solution seems to check out and it would be nice to not have the adjacency as part of the GraphDef. 

(Btw, I am traveling and won't be able to test and push anything to master for at least a few days if this solution should be merged in).

**Comment by RexYing** [comment]
@laurimi I tested and it does work. Thanks for pointing it out. Would be happy to take the pull request. 
Or I could do it myself if you are busy.

Thanks
Rex

**Comment by laurimi** [comment]
@RexYing Pull request sent. I decided to only apply the placeholder it for the adjacency matrix. It should be possible to do the same for the features as well, but I did not want to mess around with the model files since I don't feel so confident for now making modifications there.

**Comment by RexYing** [comment]
Thank very much for the contribution!
