### ISSUE TITLE
how to feed data when the number of nodes is big?

### ISSUE THREAD

**Issue by chenwgen** [williamleif/GraphSAGE#2]
Hello, I have 7 millions nodes. When I train the model, the use of memory is big,and tensorflow throws a error when create the variable of adj_info,so how to feed datas when the number of nodes is big? thanks! 
Tensorflow throws a error like this:
>ValueErrorTraceback (most recent call last)
<ipython-input-4-3dc2ce6167a4> in <module>()
----> 1 train(train_data)

><ipython-input-1-6ff86ae65e75> in train(train_data, test_data)
    149                                       max_degree=FLAGS.max_degree,
    150                                       context_pairs=context_pairs)
--> 151     adj_info = tf.Variable(tf.constant(minibatch.adj, dtype=tf.int32), trainable=False, name="adj_info")
    152 
    153     if FLAGS.model == 'graphsage_mean':

>/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.pyc in constant(value, dtype, shape, name, verify_shape)
    100   tensor_value = attr_value_pb2.AttrValue()
    101   tensor_value.tensor.CopyFrom(
--> 102       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    103   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    104   const_tensor = g.create_op(

>/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.pyc in make_tensor_proto(values, dtype, shape, verify_shape)
    431     if nparray.size * nparray.itemsize >= (1 << 31):
    432       raise ValueError(
--> 433           "Cannot create a tensor proto whose content is larger than 2GB.")
    434     tensor_proto.tensor_content = nparray.tostring()
    435     return tensor_proto

>ValueError: Cannot create a tensor proto whose content is larger than 2GB.

**Comment by RexYing** [comment]
Hi! Have you tried directly feeding the adjacency variable, so that tf does not try to create an op that copies the content from tf.constant? When building the model, initialize the tf.Variable with eg. all zeros, and then update the adjacency via feed dict before training.
