### ISSUE TITLE
Question about the deepwalk implementation

### ISSUE THREAD

**Issue by jermainewang** [williamleif/GraphSAGE#25]
Hi authors,

I have a question about the Node2Vec(DeepWalk) model you implemented. It seems that it only applies SkipGram model on a window size of 1, which means it only predicts context embeddings of immediate neighbors. Is this true?

Best,
Minjie

**Comment by williamleif** [comment]
Hi!

This is a great question: We actually use larger window sizes, but we do the random walks as a pre-processing step. In particular, for the unsupervised version you need to specify a file "<train_prefix>-walks.txt" which gives pairs of nodes that co-occur on random walks. You can specify different "window sizes" in how you generate this file.  As mentioned in our experiment, we took random walks of length 5, meaning that we used a "window size" of 10 (if that makes sense).

Cheers,
Will

**Comment by jermainewang** [comment]
Got it. Thanks for the explanation.

-Minjie

**Comment by vinaysetty** [comment]
@williamleif Just wondering why you did not use the deepwalk implementation by the authors for comparison? Did you see any difference in results?

**Comment by skx300** [comment]
> Hi!
> 
> This is a great question: We actually use larger window sizes, but we do the random walks as a pre-processing step. In particular, for the unsupervised version you need to specify a file "<train_prefix>-walks.txt" which gives pairs of nodes that co-occur on random walks. You can specify different "window sizes" in how you generate this file. As mentioned in our experiment, we took random walks of length 5, meaning that we used a "window size" of 10 (if that makes sense).
> 
> Cheers,
> Will

Hi Will, it seems like the run_random_walks function in the code only uses window_size 1, also it is hard-coded.
https://github.com/williamleif/GraphSAGE/blob/a0fdef95dca7b456dab01cb35034717c8b6dd017/graphsage/utils.py#L77-L92
