### ISSUE TITLE
Input files for simple homogeneous network

### ISSUE THREAD

**Issue by JunhengH** [williamleif/GraphSAGE#27]
I would like to test GraphSAGE on a static simple network with no features and class labels. All we know about the network is the connection of nodes. The input file is similar to: 
```
0 1 
0 2
...
```
which means node 0 is connected to 1 and 2, and the output is just embeddings based on the proximity information.

What do i need to modify the input data for getting those embeddings? thanks for your details!

**Comment by RexYing** [comment]
A commonly used technique in the past was to train the unsupervised model with input feature to be the one-hot vector indicating the index of nodes. However, note that you lose inductive capability in doing so. It also cannot scale well to very large dataset.

An alternative is to use graph-based features, such as degree, clustering coefficient, centrality, motif counts, spectral embedding etc. as input features, if you hypothesize that some or all of these features encode some form of proximity information, which is true in many cases that we observe.

**Comment by JunhengH** [comment]
Thanks! @RexYing  I will close this issue.
