### ISSUE TITLE
Issue when running the image

### ISSUE THREAD

**Issue by kenyonke** [williamleif/GraphSAGE#38]
Hi, can I ask you a simple question?
When I tried to run the image in docker image, I met a problem shown as follow:
![issuegraphsage](https://user-images.githubusercontent.com/34250873/41797839-697debc8-7663-11e8-9665-c77c9eac4cc4.JPG)
I have tried my best to fix it, but it doesn't work. Could you give me any suggestion about fixing it?
Thank you.

**Comment by pfpimenta** [comment]
I have the same problem. 
I already downgraded my tensorflow from the 1.8.0 version to the 1.3.0 one, and it didn't work.

If somebody discovers how to solve it, or has any suggestion, please let me know. Thanks.

**Comment by williamleif** [comment]
Hmm, this is strange and I can't find a fix atm.

@aksakalli (who made the image), any thoughts?

**Comment by pfpimenta** [comment]
Now it worked! Thank you!

**Comment by aksakalli** [comment]
@williamleif can we merge #40 ?

**Comment by williamleif** [comment]
Done! Thanks a ton!

**Comment by aksakalli** [comment]
Thank you, this issue can be closed now.
