### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by skeletondyh** [williamleif/GraphSAGE#41]
I think line 480 in models.py: 

neg_aff = tf.matmul(self.outputs2, tf.transpose(self.neg_outputs)) + self.neg_outputs_bias

should be self.outputs1 instead of outputs2. 

Is it a mistake?

**Comment by RexYing** [comment]
Hi, thanks for pointing this out! I believe that you are right and updated the code.

**Comment by RexYing** [comment]
though presumably that should not affect performance, because neg samples are randomly sampled from graph. They are negative samples with respect to both batch1 and batch2.
