### ISSUE TITLE
How is the initialization of identity features?

### ISSUE THREAD

**Issue by mingqiu** [williamleif/GraphSAGE#51]
Hi there,

I'm not sure how the identity features for the nodes are initialized.
I saw it's from 
`self.embeds = tf.get_variable("node_embeddings", [adj.get_shape().as_list()[0], identity_dim])`
Does it mean it initializes from some uniform distribution for a given range using `glorot_uniform_initializer`?

Thanks,
Serena

**Comment by RexYing** [comment]
Hi,
Identity features means one-hot vector feature, with each dimension indicating the identity of a specific node.
