### ISSUE TITLE
Question regarding sample numbers in layer 1 and 2

### ISSUE THREAD

**Issue by mingqiu** [williamleif/GraphSAGE#52]
Hi there,

I have a question on sample numbers in layer 1 and 2.
```
flags.DEFINE_integer('samples_1', 25, 'number of samples in layer 1')
flags.DEFINE_integer('samples_2', 10, 'number of users samples in layer 2')
```
I'm wondering which layer contains the 1-hop neighbors of the center node?
I first thought center node is 1-hop away from nodes in layer 1, and 2-hop away from nodes in layer 2.
That means the sampled result should be [1 (center node), 25 (1-hop nodes), 25*10 (2-hop nodes)].
But it turns out `samples` from `SampleAndAggregate.sample()` to have the shape [1, 10, 250]. I'm pretty confused here.

Thanks,
Serena

**Comment by yangsiran** [comment]
Hi, I think according to the code [here](https://github.com/williamleif/GraphSAGE/blob/master/graphsage/models.py#L269) The number is applied in reversed order. So sample_2 should correspond to the number 1-hop neighbors, and sample_1 should correspond to the number 2-hop neighbors.

**Comment by RexYing** [comment]
Yes that's correct. Thanks for the explanation. The layer here means GCN layer, which is in reverse order of hops.

**Comment by GxvgiuU** [comment]
Hi, I am still confused with this process. 
Suppose S_1 = 25, S_2 = 10. In this case, `S_1 != S_2`.
Suppose `h0 = hidden` in [L299](https://github.com/williamleif/GraphSAGE/blob/master/graphsage/models.py#L299)
As `h1`, in the loop at L303, can be represented by `next_hidden`, which will be filled in loop L321.
But I guess **next_hidden[0] is not aggregated on 25 neighbors, but only on 10.** 
Then, as `h2`, next_hidden[0] is aggregated on 10 neighbors, which is right.
So, I guess in the case of `s_1 != s_2`, the code is not running exactly according to the algorithm in paper?

**Comment by p1erce2023** [comment]
Hi, I am still a little confused.
suppose s1 = 25, s2 = 10. In this case s1 != s2.
so, `h0 = hidden` in [L299](https://github.com/williamleif/GraphSAGE/blob/master/graphsage/models.py#L299), `h1 = hidden_next` after L321 loop.
What confuses me is that I guess **h1[0] is aggregated on 10 neighbors, while h1[1] is aggregated on 25 neighbors**. Should these be the same? Or 1-hop nodes always aggregated on 25(s1) 2-hop nodes, while target nodes aggregated on 10(s2) 1-hop nodes?
Likely, suppose K=3, s1 = 7, s2 = 6, s3 = 5. Should the target node always aggregate on 5(s3) 1-hop nodes?
Although in practice I guess there is little difference if s_i is similar with each other.
