### ISSUE TITLE
potential bug in aggregators.py

### ISSUE THREAD

**Issue by yaronhe** [williamleif/GraphSAGE#74]
In File 'aggregators.py'
Line 159: shape of 'bias' is [self.output_dim]
Line 189: shape of 'output' is [self.output_dim*2] if flag 'Concat' is Ture
If flag 'self.bias' is True, Line 193 will raise an exception.

**Comment by RexYing** [comment]
Thanks for pointing out. The concat needs 2* the dimension for bias.
