### ISSUE TITLE
Potential bug in models.py

### ISSUE THREAD

**Issue by shayestehfard** [williamleif/GraphSAGE#85]

**Comment by shayestehfard** [comment]
In aggregate function, the hidden representation at the final layer for all nodes in batch should be returned, but you're returning hidden[0]. I am confused about this and really appreciate if you can help me understand it.

**Comment by RexYing** [comment]
Hi this is because in the minibatch training, we are aggregating each neighborhood to get representation of only 1 node. It computes N embeddings for a minibatch of N neighborhoods.

**Comment by shayestehfard** [comment]
Yes, I understand this part, but I was expecting the function to return h[-1] instead of h[0], am I wrong?

**Comment by RexYing** [comment]
Here [0] means the 0-hop nodes, which corresponds to the layer L representations.
Also refer to #39  for the explanation. In short words, 0-hop means the center node itself (nodes that are 0 distance away from center), for which we calculate the representation at the last layer.

**Comment by shayestehfard** [comment]
I see, thanks for your helpful explanation.

**Comment by shayestehfard** [comment]
Thank you so much for your helpful explanation.
