### ISSUE TITLE
Paper algorithm and l2 normalization

### ISSUE THREAD

**Issue by kkiningh** [williamleif/GraphSAGE#89]
In the paper, line 7 of Algorithm 1 and line 13 of Algorithm 2 indicates there should be an l2 normalization after every layer. However, looking at the network generated by `example_supervised.sh` in Tensorboard, I only see a single l2_normalize node at the last layer. Am I misunderstanding the algorithm? Or is there likely to be something wrong with how I'm running the example?

**Comment by RexYing** [comment]
We didn't add the layer-wise normalization in the final codebase because we find that in a lot of cases with good initialization, and with mean/max aggregation, normalization is not necessary at intermediate layers. For sum aggregation however you might consider l2 norm at every layer.

**Comment by kkiningh** [comment]
I see, thanks for the response!
