### ISSUE TITLE
Creating Feature numpy array for different kinds of node

### ISSUE THREAD

**Issue by vivekjain129** [williamleif/GraphSAGE#91]
I am trying to create input data files for the model but can't understand how to creat feat.npy file if I have two kinds of node in my graph (Let's say User and Item). Since I have 20 user attributes for every user and 50 item attributes for every item, how to create feat matrix for such graph? I would really appreciate your help on this.

**Comment by ccluqh** [comment]
> I am trying to create input data files for the model but can't understand how to creat feat.npy file if I have two kinds of node in my graph (Let's say User and Item). Since I have 20 user attributes for every user and 50 item attributes for every item, how to create feat matrix for such graph? I would really appreciate your help on this.


How did you solve it ？
