### ISSUE TITLE
Why say GraphSAGE-GCN is an inductive version of GCN

### ISSUE THREAD

**Issue by kepsail** [williamleif/GraphSAGE#93]
In the paper, there are two paragraphs as following: 
> The mean aggregator is nearly equivalent to the convolutional propagation rule used in the transductive GCN framework [17]. In particular, we can derive an inductive variant of the GCN approach by replacing lines 4 and 5 in Algorithm 1

>  Since, the “convolutional” variant of GraphSAGE is an extended, inductive version of Kipf et al’s semi-supervised GCN [17], we term this variant GraphSAGE-GCN. 

Does this mean that GCN can not be applied in an inductive setting?  
However, according to the closed issue in GCN repo [https://github.com/tkipf/gcn/issues/79](url),  GCN can be directly applied in an inductive setting.
Once trained on a graph, to learn another unseen graph, we can just feed another graph Laplacian matrix into GCN.

Why original GCN aggregator is transductive while the mean aggregator is inductive?

**Comment by RexYing** [comment]
GCN can also be trained inductively. However, one aspect of inductive learning is to be able to train on a part (not the entire graph structure) and test on unseen part of the graph. In which case one would use GraphSAGE with minibatching.

The difference between GraphSAGE-GCN and other variants are only in architecture

**Comment by kepsail** [comment]
@RexYing I see. Thanks for your explanation.

**Comment by lxw0109** [comment]
> GCN can also be trained inductively. However, one aspect of inductive learning is to be able to train on a part (not the entire graph structure) and test on unseen part of the graph. In which case one would use GraphSAGE with minibatching.
> 
> The difference between GraphSAGE-GCN and other variants are only in architecture

"The difference between GraphSAGE-GCN and other variants are only in architecture", Can you explain in detail, what's the difference of these models' architecture?
Or could you provide some articles for that.
Than you in advance, looking forward to your reply. @RexYing

**Comment by daniel620** [comment]
Based on my understanding, it is possible to directly train GCN for inductive tasks. However, the performance of GCN may differ depending on the datasets used. In order to achieve optimal performance, it is recommended to test various models and select the best one. Additionally, if the graph is particularly large, GCN's full-batch training method may pose a challenge. Therefore, I believe that the statement claiming GCN can only be trained for transductive tasks is too absolute and does not account for these nuances.
