### ISSUE TITLE
Question about eq.3 in your paper.

### ISSUE THREAD

**Issue by omiita** [williamleif/GraphSAGE#98]
Thank you for your paper and this implementation.  
I'm reading your [paper](https://arxiv.org/pdf/1706.02216.pdf) about GraphSAGE and I don't get Eq.3 about MaxPooling.  

**Why is it using h^k instead of h^(k-1) on the right hand in the Eq.3?**  
Because, the MaxPooling function seems using the previous layer's hidden vector, which is h^(k-1), to calculate the current layer's hidden vector h^k. 
That is, my question is that **why didn't use the following equation?:**  
**h^k = max( {sigma( Wpool*h^(k-1) + b) )} )**
(I omit set definition of h to avoid messy)

Thank you in advance!

**Comment by RexYing** [comment]
Hi you are right that if the left-hand side is h^k, the RHS is h^(k-1).
For paper, the aggregate_k means the aggregation function at k-th step, rather than h^k. So h^(k+1)=aggregate_k

**Comment by omiita** [comment]
Hi, 
thank you so much!!
So, eq.3 is a definition of aggregation at kth step rather than an equation.
